export const books = [{
        id: 1,
        title: 'Smokey and the Bandit',
        author: 'Burt Reynolds',
        pages: 33,
        finished: true,
    },
    {
        id: 2,
        title: 'Smokey and the Bandit',
        author: 'Burt Reynolds',
        pages: 33,
        finished: false,
    },
    {
        id: 3,
        title: 'Smokey and the Bandit',
        author: 'Burt Reynolds',
        pages: 233,
        finished: true,
    },
    {
        id: 4,
        title: 'Smokey and the Bandit',
        author: 'Burt Reynolds',
        pages: 33,
        finished: true,
    },
    {
        id: 5,
        title: 'Smokey and the Bandit',
        author: 'Burt Reynolds',
        pages: 353,
        finished: true,
    },
    {
        id: 6,
        title: 'Smokey and the Bandit',
        author: 'Burt Reynolds',
        pages: 33,
        finished: true,
    },
    {
        id: 7,
        title: 'Smokey and the Bandit',
        author: 'Burt Reynolds',
        pages: 33,
        finished: true,
    },
    {
        id: 8,
        title: 'Smokey and the Bandit',
        author: 'Burt Reynolds',
        pages: 33,
        finished: true,
    },
];